trigger:
- main  # Trigger pipeline on changes to the main branch

pool:
  vmImage: 'ubuntu-latest'  # Use a Linux agent

stages:
# Stage 1: Build
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: Build
    steps:
    - task: UseNode@1  # Use Node.js (optional, for static websites)
      inputs:
        version: '16.x'
    - script: |
        echo "Building the website..."
        ls -R  # List files for debugging
      displayName: 'Build Website'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

# Stage 2: Deploy to Azure App Service
- stage: Deploy
  displayName: 'Deploy to Azure App Service'
  dependsOn: Build
  jobs:
  - deployment: Deploy
    environment: 'Production'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'Azure-subscription'
              appType: 'webApp'
              appName: 'first'
              package: '$(Pipeline.Workspace)/drop'
              deploymentMethod: 'auto'